name: flutter_country_picker
description: A flutter package to select a country from a list of countries.

version: 3.1.0

homepage: https://github.com/ziqq/flutter_country_picker

repository: https://github.com/ziqq/flutter_country_picker

issue_tracker: https://github.com/ziqq/flutter_country_picker/issues

funding:
  - https://www.buymeacoffee.com/ziqq

platforms:
  android:
  ios:

#screenshots:
#  - description: 'Example of using the ws library to connect to a WebSocket server.'
#    path: example.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Annotations
  collection: any
  meta: any

  # UI and Widgets
  cupertino_icons: any
  grouped_list: ^5.1.2
  modal_bottom_sheet: ^3.0.0-pre
  mask_text_input_formatter: ^2.8.0

dev_dependencies:
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  # Integration tests for Flutter
  integration_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

flutter:
  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: assets/fonts/SF-Pro/SF-Pro-Rounded-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro/SF-Pro-Rounded-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro/SF-Pro-Rounded-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro/SF-Pro-Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro/SF-Pro-Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro/SF-Pro-Rounded-Light.otf
          weight: 300